.travis.yml
README.md
package-lock.json
package.json
packages/layer-selector/LayerSelector.js
packages/layer-selector/LayerSelector.stories.js
packages/layer-selector/LayerSelectorContainer.stories.js
packages/layer-selector/LayerSelectorItem.stories.js

This PR depends on https://github.com/agrc/eslint-config/pull/3 and a subsequent npm publish for the linting on travis to work. We also might need to update `package-lock.json` for this project once the eslint config is published.
Check out the commit messages for a description of the changes.

Friday's work

---

.storybook/main.js
__snapshots__/storyshots.test.js.snap
package-lock.json
package.json
packages/layer-selector/LayerSelector.js
packages/layer-selector/LayerSelector.stories.js
packages/layer-selector/LayerSelectorWithMap.stories.js

The more I thought about it, the more I thought that this was an OK solution to the issue. 
The only other idea I had was to make zoom a prop of the layer selector and then apply it in the same place. But I felt like that was a bit more disjointed having map view props mixed into the layer selector.

MapView Zoom Parameter

---

.jest/register-context.js
__snapshots__/storyshots.test.js.snap
package-lock.json
package.json
packages/layer-selector/src/LayerSelector.js
packages/layer-selector/src/LayerSelector.stories.js
packages/layer-selector/src/LayerSelectorContainer.stories.js
packages/layer-selector/src/LayerSelectorWithMap.stories.js
packages/sherlock/src/Sherlock.js
packages/sherlock/src/Sherlock.stories.js

Layer selector refactor

---

__snapshots__/storyshots.test.js.snap
packages/dartboard/READMD.md
packages/dartboard/package.json
packages/helpers/README.md
packages/helpers/package.json
packages/layer-selector/package.json
packages/layer-selector/readme.md
packages/sherlock/README.md
packages/sherlock/package.json

I'm not sure there's a great way to test this without running a lerna publish but I believe that this is an improvement.

Standardize package.json and README's between packages

---

packages/sherlock/README.md
packages/sherlock/package.json

correct errors and make the npm page look better

docs(sherlock): update readme and package for publishing

---

packages/dart-board/package.json
packages/dart-board/readme.md

correct errors and make the npm page look better

docs(dart-board): update readme and package for publishing

---

package-lock.json
packages/dart-board/package.json
packages/sherlock/package.json

July updates

---

packages/utilities/src/hooks/useGraphicManager.js

Remove console.logs

---

packages/sherlock/src/Sherlock.jsx

urlsearchparams requires new

---

.github/workflows/ci.yml
.github/workflows/release.yml
package-lock.json
package.json
packages/dart-board/package.json
packages/dart-board/src/Dartboard.jsx
packages/layer-selector/package.json
packages/mouse-trap/package.json
packages/mouse-trap/src/MouseTrap.jsx
packages/sherlock/package.json
packages/sherlock/src/Sherlock.jsx
packages/utilities/package.json
vite.config.js

This helps vite and esbuild optimize the packages without having to add any explicit configuration

Refactor to compile jsx

---

.github/workflows/ci.yml
.github/workflows/release.yml
package-lock.json
package.json
packages/dart-board/package.json
packages/dart-board/src/Dartboard.jsx
packages/layer-selector/package.json
packages/mouse-trap/package.json
packages/mouse-trap/src/MouseTrap.jsx
packages/sherlock/package.json
packages/sherlock/src/Sherlock.jsx
packages/utilities/package.json
vite.config.js

This helps vite and esbuild optimize the packages without having to add any explicit configuration
Co-authored-by: Scott Davis <stdavis@utah.gov>

compile jsx to js for vite dev optimizations

---

packages/dart-board/package.json
packages/layer-selector/package.json
packages/mouse-trap/package.json
packages/sherlock/package.json
packages/utilities/package.json

the gitignore was merging with the npm ignore and dist was not published?

Add files to package.json to correct publishing

---

packages/dart-board/package.json
packages/dart-board/src/Dartboard.jsx
packages/dart-board/src/Dartboard.stories.jsx
packages/layer-selector/package.json
packages/layer-selector/src/LayerSelector.jsx
packages/layer-selector/src/LayerSelector.stories.jsx
packages/layer-selector/src/LayerSelectorContainer.stories.jsx
packages/layer-selector/src/LayerSelectorItem.stories.jsx
packages/layer-selector/src/LayerSelectorWithMap.stories.jsx
packages/sherlock/package.json
packages/sherlock/src/Sherlock-InMap.stories.jsx
packages/sherlock/src/Sherlock.jsx
packages/sherlock/src/Sherlock.stories.jsx

add an exports to the src directory so the css can be imported
BREAKING: css has to be imported explicitly

inlined styles aren't displayed

---

packages/dart-board/src/Dartboard.jsx

this was from a vendored dartboard in parcels

fix(dart-board): update result for esrijson results

---

packages/layer-selector/src/LayerSelector.jsx
packages/layer-selector/src/LayerSelectorWithMap.stories.jsx
packages/layer-selector/src/__snapshots__/LayerSelector.test.jsx.snap

This was originally discovered in this issue: https://github.com/agrc/wfrc-wasatch-choice/issues/256

Fix layer opacity bug

---

packages/utah-design-system/src/components/Footer.jsx
packages/utah-design-system/src/components/Footer.stories.jsx
packages/utah-design-system/src/components/Link.stories.tsx
packages/utah-design-system/src/components/Link.tsx
packages/utah-design-system/src/components/SocialMedia.jsx
packages/utah-design-system/src/components/SocialMedia.stories.jsx
packages/utah-design-system/src/components/utils.ts
packages/utah-design-system/src/index.js

This has an internal and external link component

Add link component to the design system

---

packages/layer-selector/src/LayerSelector.jsx

I'll also create an issue as a reminder to bump this again to the 2024 vintage in a few months.

fix(layer-selector): bump the vintage of the color ir layer

---

.github/workflows/pull_request.yml
.storybook/main.js
.storybook/preview.js
.vscode/settings.json
package-lock.json
package.json
packages/utah-design-system/src/components/Geocode.jsx
packages/utah-design-system/src/components/Geocode.stories.jsx
packages/utah-design-system/src/components/Geocode.stories.tsx
packages/utah-design-system/src/components/Geocode.tsx
packages/utah-design-system/src/index.js
public/mockServiceWorker.js

and fix a state bug in geocode
https://storybook.js.org/blog/component-testing/
this lint error doesn't happen locally...

Try storybook component testing

---

packages/utah-design-system/src/components/Header.tsx
packages/utah-design-system/src/components/Menu.stories.tsx
packages/utah-design-system/src/components/Menu.tsx
packages/utah-design-system/src/components/TagGroup.stories.tsx
packages/utah-design-system/src/components/TagGroup.tsx
packages/utah-design-system/src/index.js

- adds a menu component 
- refactors the header to use it
- adds a tag group component

New components

---

packages/utah-design-system/src/components/Header.stories.jsx
packages/utah-design-system/src/components/Header.tsx

this allows the header to work without auth

Move auth out of header and accept as a parameter

---

packages/utah-design-system/src/components/Header.tsx

Allow auth props to be undefined

---

packages/utah-design-system/src/components/Tabs.stories.tsx
packages/utah-design-system/src/components/Tabs.tsx

feat(tabs): introduce new tabs component

---

.github/workflows/pull_request.yml
packages/utah-design-system/src/components/Spinner.tsx

fix(uds): pass aria labels to hooks to prevent warnings in console

---

packages/utah-design-system/src/components/Drawer.tsx

I think this helps a little with the jank you mentioned. I tested in atlas. I couldn't figure  out how to update the duration on the not full screen animation but it's not as jarring as it was.

style(drawer): improve animation

---

.vscode/settings.json
packages/utah-design-system/src/components/HomeButton.stories.tsx
packages/utah-design-system/src/components/HomeButton.tsx
packages/utah-design-system/src/index.ts
packages/utilities/src/hooks/index.ts
packages/utilities/src/hooks/useDefaultExtent.ts
packages/utilities/src/hooks/useViewUiPosition.ts

feat(HomeButton): introduce a button to go to a default extent

---

packages/utah-design-system/src/components/Spinner.tsx
packages/utilities/src/hooks/useViewLoading.ts

this makes the appearance look much smoother

style(busy-bar): animate opacity instead of removing the element

---

package-lock.json
packages/utah-design-system/src/components/Avatar.tsx
packages/utah-design-system/src/components/Select.tsx
packages/utah-design-system/src/components/Slider.stories.tsx
packages/utah-design-system/src/components/Slider.tsx
packages/utah-design-system/src/components/Switch.tsx
packages/utah-design-system/src/index.ts

the utah design system doesn't have any guidance but they do mention this component. I modeled the colors after the checkbox/radio button.

feat(slider): introduce a slider compontent

---

packages/utah-design-system/src/components/TextField.tsx

fix(textfield): allow input props to be passed through

---

packages/layer-selector/src/LayerSelector.jsx

Support for this was removed at react 19.

fix(layer-selector): remove use of deprecated defaultProps

---

packages/utah-design-system/src/components/Drawer.tsx

fix(drawer): update css to remove extra scrollbars

---

packages/utilities/src/hooks/useLocalStorage.ts

This error is showing up in the bikeways app. I have no idea why it's not showing up in this project but I have verified that this fixes the issue.

fix(utilities): fix type error

---

packages/utah-design-system/src/components/Checkbox.tsx

Correct light and dark pressed styles

---

packages/utah-design-system/src/components/Modal.stories.tsx
packages/utah-design-system/src/components/Modal.tsx

Ref: https://github.com/agrc/wfrc-bike-map/issues/72

fix(modal): handling scrolling on smaller devices

---

packages/tsconfigs/README.md

Does this match up with the one that you did the other day? I just wanted to put something somewhere for future reference.

docs(tsconfigs): add example for firebase function

---

packages/eslint-config/src/browser.js

ignore coverage files

---

packages/utah-design-system/src/index.ts

export firebase storage context

---

packages/tailwind-preset/README.md
packages/tailwind-preset/package.json

home page was incorrect
package was missing usage

improve readme and npm package presence

---

packages/utah-design-system/src/components/Sherlock.stories.tsx
packages/utah-design-system/src/components/Sherlock.tsx

allow contextField to be optional on the ugrcApiProvider

---

package-lock.json
packages/eslint-config/package.json
packages/eslint-config/src/browser.js
packages/layer-selector/src/LayerSelector.stories.jsx
packages/layer-selector/src/LayerSelectorContainer.stories.jsx
packages/layer-selector/src/LayerSelectorItem.stories.jsx
packages/layer-selector/src/LayerSelectorWithMap.stories.jsx
packages/mouse-trap/src/MouseTrap.stories.jsx
packages/utah-design-system/src/components/LayerSelector.stories.tsx

Add tanstack and storybook eslint plugins

---

packages/utah-design-system/src/components/Header.stories.tsx
packages/utah-design-system/src/components/Header.tsx

I'm totally open to feedback. Just trying to make this look nicer in the bikeways app.
Here's what it looks like before these changes...
and after the changes...

fix(header): make layout more friendly for smaller screens

---

packages/utah-design-system/src/contexts/FirebaseAuthProvider.tsx

this allows to pause rendering routes when they can be protected

Add a ready boolean to notify auth is setttled

---

packages/utah-design-system/src/components/Spinner.tsx

Make minDelay generic with a shorter default delay

---

packages/utah-design-system/src/components/Disclosure.stories.tsx
packages/utah-design-system/src/components/Disclosure.tsx
packages/utah-design-system/src/components/DisclosureGroup.stories.tsx
packages/utah-design-system/src/index.ts

Create disclosure implementation from utah design system

---

.vscode/settings.json
packages/esri-theme-toggle/README.md
packages/esri-theme-toggle/package.json
packages/esri-theme-toggle/src/index.js
packages/esri-theme-toggle/tests/index.html

fix(esri-theme-toggle): fix bug preventing some esri ui elements from being set to the correct theme

---

packages/utilities/src/hooks/useGraphicManager.ts
packages/utilities/src/hooks/useMapReady.ts
packages/utilities/src/hooks/useViewPointZooming.ts
packages/utilities/src/hooks/useViewUiPosition.ts
packages/utilities/src/hooks/useWebMap.ts

trying to make this all work in uic

fix(hooks): protect hooks from mapview not being ready

---

packages/utah-design-system/src/components/SocialMedia.tsx

fix(social-media): remove buzzsprout

---

package-lock.json
package.json
packages/utah-design-system/src/components/LayerSelector.stories.tsx
packages/utah-design-system/src/components/LayerSelector.test.tsx
packages/utah-design-system/src/components/LayerSelector.tsx
packages/utah-design-system/src/components/LayerSelector.utilities.ts
vite.config.ts

Enhance the layer selector by addressing color IR zoom levels, adding onBasemapChange prop, preventing duplicate layers, and optimizing layer creation for basemap tokens. 
Also, update the ArcGIS package to the latest version.

Fix layer selector bugs & add on basemap change event

---

packages/utah-design-system/src/components/ToggleButtonGroup.stories.tsx
packages/utah-design-system/src/components/ToggleButtonGroup.tsx
packages/utah-design-system/src/index.ts

feat(uds): create ToggleButtonGroup component
